version: "2"

plugins:
  duplication:  # default: 2
    enabled: true
    config:
      count_threshold: 3

checks:
  method-complexity:  # default: 5
    config:
      threshold: 15
  file-lines:  # default: 250
    enabled: false
  argument-count:  # default: 4
    enabled: false

exclude_patterns:
  - ".*"
  - "LICENSE"
  - "MANIFEST.in"
  - "*.md"
  - "ananse/_version.py"
  - "ananse/db/"
  - "docs/"
  - "*.yml"
  - "*.yaml"
  - "setup.*"
  - "tests/"
  - "versioneer.py"
