name: ananse_dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python >= 3.7
  - setuptools >=0.7
  - numpy
  - scipy >=0.9.0
  - matplotlib >=2
  - jinja2
  - pyyaml >=3.10
  - pybedtools
  - statsmodels
  - scikit-learn
  - sklearn-contrib-lightning
  - seaborn
  - pysam
  - xgboost >=0.71
  - xdg
  - diskcache
  - xxhash
  - configparser
  - six
  - future
  - gimmemotifs >=0.14.4
  - pandas=1.1.5  # tmp dependency due to gimmemotifs bug
  - tqdm
  - pillow
  - networkx
  - chest
  - dask
  - pytables
  - adjusttext
  - loguru
  - genomepy >=0.8.3
