name: ananse
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.7
  - adjusttext
  - dask
  - genomepy >=0.14
  - gimmemotifs-minimal >=0.18.0
  - loguru
  - matplotlib-base >=3.3
  - networkx
  - numpy >=1.6
  - openpyxl
  - pandas
  - pybedtools
  - pydot >=1.4.1                 # required for networkx plots
  - pygraphviz >=1.7              # required for networkx plots
  - pyranges
  - pytables                      # required for pandas.read_hfd()
  - scikit-learn
  - scipy >=1.9                   # fix in mannwhitneyu
  - seaborn-base
  - tqdm

  # Testing
  - black =23.3
  - flake8 =6.0
  - flake8-bugbear =23.3
  - pytest
  - pytest-cov

  # Docs
  - mkdocs  # test docs with `mkdocs serve`
  - mkdocs-material
