name: ananse_dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.7
  - adjusttext
  - dask
  - genomepy >=0.13.1
  - gimmemotifs-minimal >=0.17.1
  - loguru
  - matplotlib-base >=3.3
  - networkx
  - numpy >=1.6
  - openpyxl
  - pandas
  - pybedtools
  - pydot >=1.4.1                 # required for networkx plots
  - pygraphviz >=1.7              # required for networkx plots
  - pyranges
  - pytables                      # required for pandas.read_hfd()
  - scikit-learn
  - scipy >=1.5
  - seaborn-base
  - tqdm

  # Testing
  - black
  - flake8
  - flake8-bugbear
  - pytest
  - pytest-cov

  # Docs
  - mkdocs  # test docs with `mkdocs serve`
  - mkdocs-material
