name: ananse_dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python >=3.7
  - setuptools >=0.7
  - adjusttext
  - dask
  - genomepy >=0.11.0
  - gimmemotifs >=0.15.3
  - loguru
  - matplotlib >=2
  - networkx
  - numpy
  - openpyxl
  - pandas <1.3  # tmp version limit. will be fixed in gimmemotifs >0.16.1
  - pybedtools
  - pygraphviz
  - pyranges
  - pytables  # required for pandas.read_hfd()
  - scikit-learn
  - scipy >=0.9.0
  - seaborn
  - sklearn-contrib-lightning
  - tqdm

  # Testing
  - black
  - flake8
  - flake8-bugbear
  - pytest
  - pytest-cov

  # Docs
  - mkdocs  # test docs with `mkdocs serve`
  - mkdocs-material
