#!/usr/bin/env python
# Copyright (c) 2013-2019 Quan Xu <qxuchn@gmail.com>
#
# This module is free software. You can redistribute it and/or modify it under
# the terms of the MIT License, see the file COPYING included with this
# distribution.

import sys
import argparse

from genomepy import Genome
from loguru import logger

logger.remove()
logger.add(
    sys.stderr, format="<green>{time:YYYY-MM-DD HH:mm:ss}</green> | {level} | {message}"
)

from ananse import commands, __version__


class NegateAction(argparse.Action):
    def __call__(self, parser, ns, values, option):
        setattr(ns, self.dest, "include" in option)


if __name__ == "__main__":
    usage = "%(prog)s [-h] <command> [options]"
    description = "ANANSE: ANalysis Algorithm for Networks Specified by Enhancers"
    epilog = """
    commands:
        binding     infer TF binding sites in enhancer peaks
        network     built network for each sample
        influence   infer key TFs between two samples
    """
    parser = argparse.ArgumentParser(
        usage=usage,
        description=description,
        epilog=epilog,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "-v", "--version", action="version", version=f"%(prog)s v{__version__}"
    )
    subparsers = parser.add_subparsers()

    # enhancer_binding.py
    p = subparsers.add_parser(
        "binding", add_help=False
    )  # help added manually (more control)
    group = p.add_argument_group("Required arguments")
    group.add_argument(
        "-A",
        "--atac-bams",
        dest="atac_bams",
        metavar="BAM",
        help="ATAC-seq input BAM file(s), can be used alone or in combination with the -H option",
        default=None,
        nargs="+",
    )
    group.add_argument(
        "-H",
        "--histone-bams",
        dest="histone_bams",
        metavar="BAM",
        help="H3K27ac ChIP-seq input BAM file(s), can be used alone or in combibation with the -A option",
        default=None,
        nargs="+",
    )
    group = p.add_argument_group("Optional arguments")
    group.add_argument(
        "-o",
        "--outdir",
        dest="outdir",
        help="Directory where you wish to store the output (default: ./ANANSE_binding)",
        metavar="",
        default="./ANANSE_binding",
    )
    group.add_argument(
        "-R",
        "--reference",
        dest="reference",
        help="Path to reference data directory",
        metavar="PATH",
    )
    group.add_argument(
        "-r",
        "--regionfiles",
        dest="regionfiles",
        help="One or more BED format files with putative enhancer regions (e.g. BED, narrowPeak, broadPeak)",
        metavar="",
        nargs="+",  # >= 1 files
    )
    group.add_argument(
        "-g",
        "--genome",
        dest="genome",
        help="Genome name, as managed by genomepy, or path to the genome FASTA used to align the bams and peaks to",
        metavar="GENOME",
        default="hg38",
    )
    group.add_argument(
        "-d",
        "--dist-func",
        dest="dist_func",
        help="bam reads are normalized to the selected distribution (default: an empirical distribution)",
        metavar="",
        default="peak_rank_file_dist",
    )
    group.add_argument(
        "-p",
        "--pfmfile",
        dest="pfmfile",
        help="PFM file of the transcription factors to search for (default gimme.vertebrate.v5.0)",
        metavar="",
        default=None,
    )
    group.add_argument(
        "-f",
        "--factors",
        dest="factors",
        help="Transcription factors to use. Either a space-separated list or a file with one TF per line.",
        metavar="TF",
        default=None,
        nargs="*",
    )
    group.add_argument(
        "-n",
        "--ncpus",
        dest="ncpus",
        help="Number of processes to use for motif scanning",
        type=int,
        default=4,
    )
    group.add_argument(
        "--pfmscorefile",
        dest="pfmscorefile",
        help="use precomputed gimmemotifs scores (gimme scan -T -g GENOME INPUTFILE)",
        metavar="",
        default=None,
    )
    group.add_argument(
        "-h", "--help", action="help", help="show this help message and exit"
    )
    p.set_defaults(func=commands.binding)

    # network.py
    p = subparsers.add_parser("network", add_help=False)
    group = p.add_argument_group("required arguments")
    group.add_argument(
        "-b",
        "--binding",
        dest="binding",
        help="All TFs binding file",
        metavar="FILE",
    )
    group.add_argument(
        "-e",
        "--expression",
        dest="fin_expression",
        help="Expression scores",
        metavar="FILE",
        nargs="*",
    )
    group.add_argument(
        "-o",
        "--output",
        required=True,
        dest="outfile",
        help="Output file",
        metavar="FILE",
        default=None,
    )
    group = p.add_argument_group("optional arguments")
    group.add_argument(
        "-g",
        "--genome",
        dest="genome",
        help="Genome",
        metavar="NAME",
        default="hg38",
    )
    group.add_argument(
        "-a",
        "--annotation",
        dest="annotation",
        help="Gene annotation in BED12 format",
        metavar="BED",
    )
    group.add_argument(
        "-c",
        "--corrfiles",
        dest="corrfiles",
        help="Files with correlation",
        metavar="FILE",
        nargs="*",
    )
    group.add_argument(
        "-n",
        "--ncore",
        dest="ncore",
        help="Number of core used",
        type=int,
    )
    group.add_argument(
        "--include-promoter",
        "--exclude-promoter",
        default=False,
        help="Include or exclude promoter peaks (<= TSS +/- 2kb) in network inference. By default promoter peaks are excluded.",
        dest="include_promoter",
        action=NegateAction,
        nargs=0,
    )
    group.add_argument(
        "--include-enhancer",
        "--exclude-enhancer",
        default=True,
        help="Include or exclude enhancer peaks (> TSS +/- 2kb) in network inference. By default enhancer peaks are included.",
        dest="include_enhancer",
        action=NegateAction,
        nargs=0,
    )
    group.add_argument(
        "-h", "--help", action="help", help="show this help message and exit"
    )

    # p.add_argument(
    #     "-r",
    #     "--enhancers",
    #     required=True,
    #     dest="fin_rpkm",
    #     help="BED file with RPKM on the 4th column",
    #     metavar="FILE",
    # )
    # p.add_argument(
    #     "-f",
    #     "--filter_promoter",
    #     dest="fpomoter",
    #     help="Filter promoters, True or False, input should be either 'True' or 'False'.",
    #     metavar="NAME",
    #     type=ast.literal_eval,
    #     default=True,
    # )

    # This not used currently
    # group.add_argument(
    #     "-i",
    #     "--impute",
    #     dest="impute",
    #     help="Impute missing values",
    #     default=False,
    #     action="store_true",
    # )

    p.set_defaults(func=commands.network)

    # # network.py
    # p = subparsers.add_parser("network")
    # p.add_argument(
    #     "-f",
    #     "--interaction",
    #     dest="features",
    #     help="HDF5 file with features",
    #     metavar="FILE",
    #     default=None,
    #     required=True,
    # )
    # p.add_argument(
    #     "-o",
    #     "--outfile",
    #     required=True,
    #     dest="outfile",
    #     help="Output file",
    #     metavar="FILE",
    #     default=None,
    # )
    # p.add_argument(
    #     "-i",
    #     "--impute",
    #     dest="impute",
    #     help="Impute missing values",
    #     default=False,
    #     action="store_true",
    # )
    # p.set_defaults(func=commands.network)

    # influence.py
    p = subparsers.add_parser("influence", add_help=False)

    group = p.add_argument_group("required arguments")
    group.add_argument(
        "-t",
        "--target",
        dest="Gaf",
        help="network in second cell",
        metavar="FILE",
        default=None,
    )
    group.add_argument(
        "-d",
        "--degenes",
        dest="expression",
        help="DE genes file",
        metavar="FILE",
    )
    group.add_argument(
        "-o",
        "--outfile",
        required=True,
        dest="outfile",
        help="Output file",
        metavar="FILE",
        default=None,
    )
    group = p.add_argument_group("optional arguments")
    group.add_argument(
        "-s",
        "--source",
        dest="Gbf",
        help="network in first cell",
        metavar="FILE",
        default=None,
    )
    group.add_argument(
        "-i",
        "--edges",
        dest="edges",
        help="Number of top edges used",
        type=int,
        default=100000,
    )
    group.add_argument(
        "-e",
        "--expression",
        dest="fin_expression",
        help="Expression scores in first cell",
        metavar="FILE",
    )
    group.add_argument(
        "-p",
        "--plot",
        dest="plot",
        help="Create influence score plot.",
        action="store_true",
        default=False,
    )
    group.add_argument(
        "-n",
        "--ncore",
        dest="ncore",
        help="Number of core used",
        type=int,
    )
    group.add_argument(
        "-h", "--help", action="help", help="show this help message and exit"
    )
    p.set_defaults(func=commands.influence)

    if "help" in sys.argv:
        parser.print_help()
    else:
        args = parser.parse_args()

        if hasattr(args, "genome"):
            if args.genome is not None:
                try:
                    Genome(args.genome)
                except Exception:  # noqa
                    logger.exception(
                        f"Genome {args.genome} not found. Have you installed your genome with genomepy? "
                        "See https://github.com/vanheeringen-lab/genomepy for details. "
                        "Alternatively, you can specify a FASTA file."
                    )

        if args.func.__name__.startswith("run_"):
            args.func(**vars(args))
        else:
            args.func(args)
